### ISSUE TITLE
Could not gather tasks for OS League Tools Export

### ISSUE THREAD

**Issue by Jamboona** [tylerthardy/osleague-runelite-plugin#2] opened 2020-11-25 14:37 UTC
![Capture](https://user-images.githubusercontent.com/75029508/100241479-a4ce1300-2f2b-11eb-9a33-1bb73a6b4b46.PNG)
When bringing up the windows to export the task data, it spams the error message over and over.

Tried removing and reinstalling plugin, same with Runelite. Neither fixed the issue.

**Comment by SlyyJacob** [comment] 2020-11-25 16:13
Same issue here, worked fine yesterday.

**Comment by tr33s** [comment] 2020-11-26 06:49
The widget ids have changed since the update on 24/11, because of all that is hardcoded it's more than a couple lines to change. Please fix asap.

**Comment by cannonpalms** [comment] 2020-11-29 02:35
This is possibly an issue caused by the new filters deployed for this menu, e.g. "Unlocked" regions only. The author seems to be MIA, so I'll take a look in the meantime. Ultimately, we'll still need him to deploy an update.

**Comment by cannonpalms** [comment] 2020-11-29 02:44
I have no idea. The latest implementation on master reads as though it would work just fine. @SlyJacobTheBeast @Jamboona Are you still experiencing this issue? It is possible that @tylerthardy resolved this 3 days ago with c7d8996.

**Comment by tylerthardy** [comment] 2020-11-29 02:45
The issue was caused by Jagex duplicating a task, and having the task count hard coded. @chaiinchomp removed the hardcoded count, because $11 🦀 . It should be fixed.

**Closed as completed** 2020-11-29 03:08 UTC
